Create Standalone Module
RichardYang40148/mgeval pull request #4
Opened 2021-07-27 17:40 UTC by ghalestrilo

## Contribution

This PR adds code for running `mgeval` as a standalone module, including:
  - A `__main__.py` file
  - An update to the documentation, indicating how to use the script
  - A bugfix for `bar_used_pitch` calculation

## Context

I'm developing a system to evaluate the output of different music generationg RNNs, and I'm using `mgeval` to evaluate these models. The system uses python 3 and therefore it's incompatible with `mgeval` as a library. The workaround I found is to run `mgeval` as a standalone module, producing the metrics and saving them to a pickle.

I think this could be an useful feature for other people as well, and I'm willing to make any required adjustments

2021-07-29 20:25 UTC, RichardYang40148 requested changes
Appreciate the contribution!
Everything looks good.
There a few `.pyc` files that are pushed along with the codes, a little touch up in the gitignore will do.

2021-07-29 20:25 UTC, RichardYang40148 commented on .gitignore
> +start.sh
```suggestion
start.sh
*.pyc
```

2021-07-31 17:15 UTC, ghalestrilo commented
Great! I removed the pycache files, should be good now

2021-08-02 16:13 UTC, RichardYang40148 approved these changes
Thanks!

2021-08-02 16:13 UTC, merged